version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=DigiUser
      - DB_PASSWORD=Babish@1998
      - DB_NAME=DigitalCard
    ports:
      - "8080:8080"
    entrypoint:
      [
        "sh",
        "-c",
        "npm run dev",
      ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
