version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: node_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint:
      [
        "sh",
        "-c",
        "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev",
      ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
